### ISSUE TITLE
changing the SDA/SCL pins

### ISSUE THREAD

**Issue by kaosbeat** [adafruit/Adafruit_Trellis_Library#11]
Trellistest compiles and uploads works for the RFduino, although I don't know where to set the SDA and SCL pins. So I added 

```
int SCLpin = 3;
int SDApin = 4;
```
in the beginning and 
```
Wire.beginOnPins(SCLpin, SDApin);
```

in void setup()

but still no light. 3.3V not enough to power the LEDS? my Trellis works on a regular arduino. Or is it a pinout problem?  can I set the SCL/SDA pins somewhere in the trellissetup? The serial output shows the test code so that means the SCL/SDA is working right?

would it be safe for my rfduino to connect the 5V pin to a 5V power source or will the SDA/SCL pins be fried?

 
thanks

**Comment by ladyada** [comment]
This sounds like a good question for RFDuino, they must have something 'different' that makes it not Arduino compatible :)

**Comment by kaosbeat** [comment]
not sure, I've been grinding through this all day now, As the I2C scanner works, trellis is discovered fine on the RFduino using arduino code, but I'm not getting any response from the trellis using the trellis library. I don't know where to check for the I2C pinout in trellis, how can I be sure it's using the SDA/SCL? 

I tested the signal using using a scope ... and nothing's on the line, while signal clear on my other test.
![image](https://cloud.githubusercontent.com/assets/204628/9283458/4c7f53ec-42d4-11e5-950b-2d41b408e814.png)

so simple question is, how to force trellis to use predefined SDL/SCA pins? 

wireless trellis you know :) would be cool!

**Comment by tolson2000** [comment]
It works if you connect to the default pins for SCL and SDA which is pins 5 and 6. If you want to change locations to 3 and 4 then you have to put the Wire.beginOnPins(SCLpin, SDApin); in the library, not the setup() since that is where Wire.begin is defined.

**Comment by kaosbeat** [comment]
@tolson2000 I can confirm it works now! I did use the default 5 SCL, 6 SDA  pins

**Comment by SandroGrassia** [comment]
tolson2000 can you please explain where Wire.beginOnPins(SCLpin, SDApin) must be written in the library?
Thank you

**Comment by tolson2000** [comment]
Replace the Wire.begin() with Wire.beginOnPins(SCLpin, SDApin).


void Adafruit_Trellis::begin(uint8_t_addr = 0x70) {
  i2c_addr = _addr;

 #Wire.begin();
 Wire.beginOnPins(3,4); #for example

  Wire.beginTransmission(i2c_addr);

  * * *

**Comment by bigoper** [comment]
Hi @tolson2000 
I can't seem to find that in the `Adafruit_SSD1306.h` library.
Could you help me out here?

Thanks!

**Comment by tolson2000** [comment]
Hi @bigoper
It is done in the .h file. Look in the .cpp file.

I am curious. Are you still using the RFduino somehow?

**Comment by bigoper** [comment]
@tolson2000 
Hi,

I'm was trying to get Mongoose-os (limited javascript) with ESP8266 (NodeMCu v1 Lolin) to work with the SSD1306 library.
I needed to change the `default` pins since they are diff for my board.

I gave up on Mongoose-os, and went back to Espressif :)
Everything just works and lots of support.

Avi.

**Comment by 4r53N1ck** [comment]
To those who want to change the default I2C connections using Adafruit_SSD1306.h lib, try the following:

Chinese displays only:
Change your display address to 0x3C (even if you have the 128x64).

Then, after this line on your setup function
`Serial.begin(115200);`
add this to use (IE) D3 (SDA) and D4 (SCL):
`Wire.begin(D3,D4);`

So, your code should look like this:
`#include <SPI.h>
#include <Wire.h>
#include <Adafruit_GFX.h>
#include <Adafruit_SSD1306.h>

#define SCREEN_WIDTH 128 // OLED display width, in pixels
#define SCREEN_HEIGHT 64 // OLED display height, in pixels

// Declaration for an SSD1306 display connected to I2C (SDA, SCL pins)
// The pins for I2C are defined by the Wire-library. 
// On an arduino UNO:       A4(SDA), A5(SCL)
// On an arduino MEGA 2560: 20(SDA), 21(SCL)
// On an arduino LEONARDO:   2(SDA),  3(SCL), ...
#define OLED_RESET     -1 // Reset pin # (or -1 if sharing Arduino reset pin)
#define SCREEN_ADDRESS 0x3C ///< See datasheet for Address; 0x3D for 128x64, 0x3C for 128x32
....

....

void setup() {
  Serial.begin(115200);
  Wire.begin(D3,D4);

  // SSD1306_SWITCHCAPVCC = generate display voltage from 3.3V internally
  if(!display.begin(SSD1306_SWITCHCAPVCC, SCREEN_ADDRESS)) {
    Serial.println(F("SSD1306 allocation failed"));
    for(;;); // Don't proceed, loop forever
  }
...
...
`

**Comment by tauzn-clock** [comment]
Thank you @4r53N1ck, this worked for me.
To recap, you must do two things
- Wire.begin() allows you to redefine the SDA and SDL pins
- Change SCREEN_ADDRESS from 0x3D to 0x3C
